# Generated by Django 4.0.4 on 2022-04-11 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('city', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('aadhar_no', models.BigIntegerField(max_length=12, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=3)),
                ('phone_number', models.BigIntegerField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodmatch.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('aadhar_no', models.BigIntegerField(max_length=12, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=3)),
                ('phone_number', models.BigIntegerField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('hemoglobin', models.FloatField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodmatch.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18)), name='age_check'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.CheckConstraint(check=models.Q(('age__lte', 65)), name='age_check_high'),
        ),
        migrations.AddConstraint(
            model_name='donor',
            constraint=models.CheckConstraint(check=models.Q(('hemoglobin__gte', 13)), name='hemoglobin_check'),
        ),
    ]
