# Generated by Django 4.0.4 on 2022-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodmatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='receiver',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=100),
        ),
    ]
